export const EXAM_DURATION_SECONDS = 25 * 60;
export const EXAM_QUESTION_COUNT = 40;

export const CLASS_OPTIONS = [
  'JSS1 A',
  'JSS1 B',
  'JSS1 C',
  'JSS1 D',
  'JSS2 A',
  'JSS2 B',
  'JSS2 C',
  'JSS2 D',
  'JSS3 A',
  'JSS3 B',
  'JSS3 C',
  'JSS3 D',
  'SS1 A',
  'SS1 B',
  'SS1 C',
  'SS1 D',
  'SS2 A',
  'SS2 B',
  'SS2 C',
  'SS2 D',
];

export const DEFAULT_QUESTION_BANK = [
  {
    id: 'Q001',
    topic: 'basics',
    type: 'single',
    text: 'Which one is an input device?',
    options: [
      { id: 'A', text: 'Keyboard' },
      { id: 'B', text: 'Monitor' },
      { id: 'C', text: 'Speaker' },
      { id: 'D', text: 'Printer' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q002',
    topic: 'basics',
    type: 'single',
    text: 'Which one is an output device?',
    options: [
      { id: 'A', text: 'Mouse' },
      { id: 'B', text: 'Monitor' },
      { id: 'C', text: 'Keyboard' },
      { id: 'D', text: 'Scanner' },
    ],
    correctOptionIds: ['B'],
  },
  {
    id: 'Q003',
    topic: 'basics',
    type: 'single',
    text: 'Pick the odd one out.',
    options: [
      { id: 'A', text: 'Keyboard' },
      { id: 'B', text: 'Mouse' },
      { id: 'C', text: 'Scanner' },
      { id: 'D', text: 'Speaker' },
    ],
    correctOptionIds: ['D'],
  },
  {
    id: 'Q004',
    topic: 'basics',
    type: 'single',
    text: 'What does a monitor do?',
    options: [
      { id: 'A', text: 'Shows output on screen' },
      { id: 'B', text: 'Prints to paper' },
      { id: 'C', text: 'Scans book pages' },
      { id: 'D', text: 'Records voice' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q005',
    topic: 'basics',
    type: 'single',
    text: 'What does a printer do?',
    options: [
      { id: 'A', text: 'Prints on paper' },
      { id: 'B', text: 'Opens websites' },
      { id: 'C', text: 'Moves pointer' },
      { id: 'D', text: 'Stores files in cloud' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q006',
    topic: 'internet',
    type: 'single',
    text: 'The internet is...',
    options: [
      { id: 'A', text: 'A big network of connected computers' },
      { id: 'B', text: 'A keyboard type' },
      { id: 'C', text: 'A monitor brand' },
      { id: 'D', text: 'A game pad' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q007',
    topic: 'internet',
    type: 'single',
    text: 'Which app is used to open a website?',
    options: [
      { id: 'A', text: 'Browser' },
      { id: 'B', text: 'Calculator' },
      { id: 'C', text: 'Paint' },
      { id: 'D', text: 'Notepad' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q008',
    topic: 'internet',
    type: 'single',
    text: 'A website address is called...',
    options: [
      { id: 'A', text: 'URL' },
      { id: 'B', text: 'Folder' },
      { id: 'C', text: 'Icon' },
      { id: 'D', text: 'Wallpaper' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q009',
    topic: 'internet',
    type: 'single',
    text: 'The first page of a website is often called...',
    options: [
      { id: 'A', text: 'Home page' },
      { id: 'B', text: 'Final page' },
      { id: 'C', text: 'Drawing page' },
      { id: 'D', text: 'Sound page' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q010',
    topic: 'internet',
    type: 'multi',
    text: 'Pick all web browsers.',
    options: [
      { id: 'A', text: 'Google Chrome' },
      { id: 'B', text: 'Microsoft Edge' },
      { id: 'C', text: 'Firefox' },
      { id: 'D', text: 'PowerPoint' },
    ],
    correctOptionIds: ['A', 'B', 'C'],
  },
  {
    id: 'Q011',
    topic: 'web',
    type: 'single',
    text: 'HTML is used to...',
    options: [
      { id: 'A', text: 'Build webpage structure' },
      { id: 'B', text: 'Play songs' },
      { id: 'C', text: 'Print books' },
      { id: 'D', text: 'Charge laptop' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q012',
    topic: 'web',
    type: 'single',
    text: 'CSS is used to...',
    options: [
      { id: 'A', text: 'Style colors and sizes' },
      { id: 'B', text: 'Open internet' },
      { id: 'C', text: 'Delete folders' },
      { id: 'D', text: 'Turn on monitor' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q013',
    topic: 'web',
    type: 'single',
    text: 'JavaScript helps a webpage to...',
    options: [
      { id: 'A', text: 'Respond to clicks' },
      { id: 'B', text: 'Become a keyboard' },
      { id: 'C', text: 'Format hard disk' },
      { id: 'D', text: 'Wash clothes' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q014',
    topic: 'web',
    type: 'single',
    text: 'Which extension is for HTML files?',
    options: [
      { id: 'A', text: '.html' },
      { id: 'B', text: '.css' },
      { id: 'C', text: '.js' },
      { id: 'D', text: '.mp3' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q015',
    topic: 'web',
    type: 'single',
    text: 'Which extension is for CSS files?',
    options: [
      { id: 'A', text: '.css' },
      { id: 'B', text: '.html' },
      { id: 'C', text: '.png' },
      { id: 'D', text: '.wav' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q016',
    topic: 'web',
    type: 'single',
    text: 'Which extension is for JavaScript files?',
    options: [
      { id: 'A', text: '.jpg' },
      { id: 'B', text: '.js' },
      { id: 'C', text: '.pdf' },
      { id: 'D', text: '.docx' },
    ],
    correctOptionIds: ['B'],
  },
  {
    id: 'Q017',
    topic: 'web',
    type: 'multi',
    text: 'Pick all parts used in a simple website.',
    options: [
      { id: 'A', text: 'HTML' },
      { id: 'B', text: 'CSS' },
      { id: 'C', text: 'JavaScript' },
      { id: 'D', text: 'Bluetooth' },
    ],
    correctOptionIds: ['A', 'B', 'C'],
  },
  {
    id: 'Q018',
    topic: 'coding',
    type: 'single',
    text: 'Who is a programmer?',
    options: [
      { id: 'A', text: 'A person who writes code' },
      { id: 'B', text: 'A person who drives a bus' },
      { id: 'C', text: 'A person who sells books' },
      { id: 'D', text: 'A person who paints houses' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q019',
    topic: 'coding',
    type: 'single',
    text: 'A programming language is...',
    options: [
      { id: 'A', text: 'A way to write computer instructions' },
      { id: 'B', text: 'A keyboard cable' },
      { id: 'C', text: 'A laptop battery' },
      { id: 'D', text: 'A printer button' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q020',
    topic: 'coding',
    type: 'single',
    text: 'A program is...',
    options: [
      { id: 'A', text: 'A set of instructions for a computer' },
      { id: 'B', text: 'A mouse pad' },
      { id: 'C', text: 'A wall clock' },
      { id: 'D', text: 'A desk fan' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q021',
    topic: 'basics',
    type: 'single',
    text: 'Which one is a storage device?',
    options: [
      { id: 'A', text: 'USB flash drive' },
      { id: 'B', text: 'Mouse pad' },
      { id: 'C', text: 'Projector' },
      { id: 'D', text: 'Speaker stand' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q022',
    topic: 'basics',
    type: 'multi',
    text: 'Pick all output devices.',
    options: [
      { id: 'A', text: 'Monitor' },
      { id: 'B', text: 'Printer' },
      { id: 'C', text: 'Speaker' },
      { id: 'D', text: 'Keyboard' },
    ],
    correctOptionIds: ['A', 'B', 'C'],
  },
  {
    id: 'Q023',
    topic: 'basics',
    type: 'multi',
    text: 'Pick all input devices.',
    options: [
      { id: 'A', text: 'Mouse' },
      { id: 'B', text: 'Keyboard' },
      { id: 'C', text: 'Scanner' },
      { id: 'D', text: 'Monitor' },
    ],
    correctOptionIds: ['A', 'B', 'C'],
  },

  {
    id: 'Q024',
    topic: 'navigation',
    type: 'single',
    text: 'Right-click usually opens...',
    options: [
      { id: 'A', text: 'A shortcut menu' },
      { id: 'B', text: 'The power button' },
      { id: 'C', text: 'The internet' },
      { id: 'D', text: 'A camera app' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q025',
    topic: 'navigation',
    type: 'single',
    text: 'To create a folder on desktop, first do...',
    options: [
      { id: 'A', text: 'Right-click on empty desktop area' },
      { id: 'B', text: 'Turn off computer' },
      { id: 'C', text: 'Press Caps Lock' },
      { id: 'D', text: 'Remove battery' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q026',
    topic: 'navigation',
    type: 'single',
    text: 'To rename a file, choose...',
    options: [
      { id: 'A', text: 'Rename' },
      { id: 'B', text: 'Delete' },
      { id: 'C', text: 'Refresh' },
      { id: 'D', text: 'Print' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q027',
    topic: 'navigation',
    type: 'single',
    text: 'Which shortcut opens File Explorer?',
    options: [
      { id: 'A', text: 'Windows + E' },
      { id: 'B', text: 'Ctrl + P' },
      { id: 'C', text: 'Alt + F4' },
      { id: 'D', text: 'Ctrl + N' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q028',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for copy is...',
    options: [
      { id: 'A', text: 'Ctrl + C' },
      { id: 'B', text: 'Ctrl + X' },
      { id: 'C', text: 'Ctrl + V' },
      { id: 'D', text: 'Ctrl + Z' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q029',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for paste is...',
    options: [
      { id: 'A', text: 'Ctrl + Z' },
      { id: 'B', text: 'Ctrl + V' },
      { id: 'C', text: 'Ctrl + C' },
      { id: 'D', text: 'Ctrl + S' },
    ],
    correctOptionIds: ['B'],
  },
  {
    id: 'Q030',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for cut is...',
    options: [
      { id: 'A', text: 'Ctrl + X' },
      { id: 'B', text: 'Ctrl + A' },
      { id: 'C', text: 'Ctrl + P' },
      { id: 'D', text: 'Ctrl + R' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q031',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for undo is...',
    options: [
      { id: 'A', text: 'Ctrl + Z' },
      { id: 'B', text: 'Ctrl + V' },
      { id: 'C', text: 'Ctrl + T' },
      { id: 'D', text: 'Ctrl + W' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q032',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for select all is...',
    options: [
      { id: 'A', text: 'Ctrl + S' },
      { id: 'B', text: 'Ctrl + A' },
      { id: 'C', text: 'Ctrl + D' },
      { id: 'D', text: 'Ctrl + E' },
    ],
    correctOptionIds: ['B'],
  },
  {
    id: 'Q033',
    topic: 'navigation',
    type: 'single',
    text: 'Which key can refresh desktop or browser page?',
    options: [
      { id: 'A', text: 'F5' },
      { id: 'B', text: 'Esc' },
      { id: 'C', text: 'Shift' },
      { id: 'D', text: 'Tab' },
    ],
    correctOptionIds: ['A'],
  },

  {
    id: 'Q034',
    topic: 'vscode',
    type: 'single',
    text: 'Which app did we use in class to write code?',
    options: [
      { id: 'A', text: 'Visual Studio Code' },
      { id: 'B', text: 'Calculator' },
      { id: 'C', text: 'Zoom' },
      { id: 'D', text: 'Snipping Tool' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q035',
    topic: 'vscode',
    type: 'single',
    text: 'In VS Code, which side panel shows your files?',
    options: [
      { id: 'A', text: 'Explorer' },
      { id: 'B', text: 'Terminal' },
      { id: 'C', text: 'Status Bar' },
      { id: 'D', text: 'Title Bar' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q036',
    topic: 'vscode',
    type: 'single',
    text: 'In VS Code, to create a new file, click...',
    options: [
      { id: 'A', text: 'New File' },
      { id: 'B', text: 'Delete File' },
      { id: 'C', text: 'Print File' },
      { id: 'D', text: 'Close Folder' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q037',
    topic: 'vscode',
    type: 'single',
    text: 'Shortcut to save in VS Code is...',
    options: [
      { id: 'A', text: 'Ctrl + S' },
      { id: 'B', text: 'Ctrl + G' },
      { id: 'C', text: 'Ctrl + L' },
      { id: 'D', text: 'Ctrl + Y' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q038',
    topic: 'vscode',
    type: 'single',
    text: 'To open a folder in VS Code, go to...',
    options: [
      { id: 'A', text: 'File > Open Folder' },
      { id: 'B', text: 'Edit > Copy' },
      { id: 'C', text: 'View > Zoom In' },
      { id: 'D', text: 'Help > About' },
    ],
    correctOptionIds: ['A'],
  },

  {
    id: 'Q039',
    topic: 'web',
    type: 'single',
    text: 'In HTML, <h1> is used for...',
    options: [
      { id: 'A', text: 'Main heading text' },
      { id: 'B', text: 'Playing music' },
      { id: 'C', text: 'Drawing circles' },
      { id: 'D', text: 'Deleting folders' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q040',
    topic: 'web',
    type: 'single',
    text: 'Choose the correct match.',
    options: [
      { id: 'A', text: 'HTML = structure, CSS = style, JS = action' },
      { id: 'B', text: 'HTML = style, CSS = action, JS = structure' },
      { id: 'C', text: 'HTML = browser, CSS = keyboard, JS = printer' },
      { id: 'D', text: 'HTML = internet, CSS = folder, JS = mouse' },
    ],
    correctOptionIds: ['A'],
  },
];
