export const EXAM_DURATION_SECONDS = 30 * 60;
export const EXAM_QUESTION_COUNT = 40;

export const CLASS_OPTIONS = [
  'JSS1',
  'JSS2',
  'JSS3',
  'SS1',
  'SS2',
];

export const DEFAULT_QUESTION_BANK = [
  {
    id: 'Q001',
    topic: 'basics',
    type: 'single',
    text: 'Which of the following is an IDE(Integrated Development Environment)?',
    options: [
      { id: 'A', text: 'VSCode' },
      { id: 'B', text: 'Chrome' },
      { id: 'C', text: 'File Explorer' },
      { id: 'D', text: 'Scratch' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q002',
    topic: 'web',
    type: 'multi',
    text: 'Every html file is divided into two sections. They are ______ and ______?',
    options: [
      { id: 'A', text: 'Head' },
      { id: 'B', text: 'Title' },
      { id: 'C', text: 'Body' },
      { id: 'D', text: 'Footer' },
    ],
    correctOptionIds: ['A', 'C'],
  },
  {
    id: 'Q003',
    topic: 'web',
    type: 'single',
    text: 'Pick the odd one out.',
    options: [
      { id: 'A', text: 'Interal Styling' },
      { id: 'B', text: 'External Styling' },
      { id: 'C', text: 'Inline Styling' },
      { id: 'D', text: 'Outline Styling' },
    ],
    correctOptionIds: ['D'],
  },
  {
    id: 'Q004',
    topic: 'web',
    type: 'single',
    text: 'What html tag creates a list that is numbered?',
    options: [
      { id: 'A', text: '<li>' },
      { id: 'B', text: '<ol>' },
      { id: 'C', text: '<ul>' },
      { id: 'D', text: '<dl>' },
    ],
    correctOptionIds: ['B'],
  },
  {
    id: 'Q005',
    topic: 'web',
    type: 'single',
    text: 'HTML is for structure, CSS is for _______, JavaScript is for action.',
    options: [
      { id: 'A', text: 'Styling' },
      { id: 'B', text: 'Content' },
      { id: 'C', text: 'Browsing' },
      { id: 'D', text: 'Playing' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q006',
    topic: 'internet',
    type: 'single',
    text: 'The internet is...',
    options: [
      { id: 'A', text: 'A big network of connected computers' },
      { id: 'B', text: 'A keyboard type' },
      { id: 'C', text: 'A monitor brand' },
      { id: 'D', text: 'A game pad' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q007',
    topic: 'internet',
    type: 'single',
    text: 'Which app is used to open a website?',
    options: [
      { id: 'A', text: 'Browser' },
      { id: 'B', text: 'Calculator' },
      { id: 'C', text: 'Paint' },
      { id: 'D', text: 'Notepad' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q008',
    topic: 'internet',
    type: 'single',
    text: 'A website address is called...',
    options: [
      { id: 'A', text: 'URL' },
      { id: 'B', text: 'Folder' },
      { id: 'C', text: 'Icon' },
      { id: 'D', text: 'Wallpaper' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q009',
    topic: 'web',
    type: 'single',
    text: 'What type of styling involves linking your html file to an external css file?',
    options: [
      { id: 'A', text: 'Inline styling' },
      { id: 'B', text: 'Internal Styling' },
      { id: 'C', text: 'External Styling' },
      { id: 'D', text: 'Outline styling' },
    ],
    correctOptionIds: ['C'],
  },
  {
    id: 'Q010',
    topic: 'internet',
    type: 'multi',
    text: 'Pick all web browsers.',
    options: [
      { id: 'A', text: 'Google Chrome' },
      { id: 'B', text: 'Microsoft Edge' },
      { id: 'C', text: 'Firefox' },
      { id: 'D', text: 'PowerPoint' },
    ],
    correctOptionIds: ['A', 'B', 'C'],
  },
  {
    id: 'Q011',
    topic: 'web',
    type: 'single',
    text: 'HTML is used to...',
    options: [
      { id: 'A', text: 'Build webpage structure' },
      { id: 'B', text: 'Play songs' },
      { id: 'C', text: 'Print books' },
      { id: 'D', text: 'Charge laptop' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q012',
    topic: 'web',
    type: 'single',
    text: 'CSS is used to...',
    options: [
      { id: 'A', text: 'Style colors and sizes' },
      { id: 'B', text: 'Open internet' },
      { id: 'C', text: 'Delete folders' },
      { id: 'D', text: 'Turn on monitor' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q013',
    topic: 'web',
    type: 'single',
    text: 'JavaScript helps a webpage to...',
    options: [
      { id: 'A', text: 'Respond to actions' },
      { id: 'B', text: 'Become a keyboard' },
      { id: 'C', text: 'Format hard disk' },
      { id: 'D', text: 'Wash clothes' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q014',
    topic: 'web',
    type: 'single',
    text: 'Which extension is for HTML files?',
    options: [
      { id: 'A', text: '.html' },
      { id: 'B', text: '.css' },
      { id: 'C', text: '.js' },
      { id: 'D', text: '.mp3' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q015',
    topic: 'web',
    type: 'single',
    text: 'Which extension is for CSS files?',
    options: [
      { id: 'A', text: '.css' },
      { id: 'B', text: '.html' },
      { id: 'C', text: '.png' },
      { id: 'D', text: '.wav' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q016',
    topic: 'basics',
    type: 'single',
    text: 'What is the use of <DOCTYPE html> in html code?',
    options: [
      { id: 'A', text: 'It is a comment' },
      { id: 'B', text: 'It tells the browser that this is a webpage' },
      { id: 'C', text: 'It adds color to the webpage' },
      { id: 'D', text: 'It is a paragraph tag' },
    ],
    correctOptionIds: ['B'],
  },
  {
    id: 'Q017',
    topic: 'web',
    type: 'multi',
    text: 'Pick all parts used in a simple website.',
    options: [
      { id: 'A', text: 'HTML' },
      { id: 'B', text: 'CSS' },
      { id: 'C', text: 'JavaScript' },
      { id: 'D', text: 'Bluetooth' },
    ],
    correctOptionIds: ['A', 'B', 'C'],
  },
  {
    id: 'Q018',
    topic: 'coding',
    type: 'single',
    text: 'Who is a programmer?',
    options: [
      { id: 'A', text: 'A person who writes code' },
      { id: 'B', text: 'A person who drives a bus' },
      { id: 'C', text: 'A person who sells books' },
      { id: 'D', text: 'A person who paints houses' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q019',
    topic: 'coding',
    type: 'single',
    text: 'A programming language is...',
    options: [
      { id: 'A', text: 'A way to communicaate instructions to the computer' },
      { id: 'B', text: 'A language spoken in Cyberland' },
      { id: 'C', text: 'French' },
      { id: 'D', text: 'A printer button' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q020',
    topic: 'coding',
    type: 'single',
    text: 'A computer program is...',
    options: [
      { id: 'A', text: 'A set of instructions for a computer' },
      { id: 'B', text: 'A game we play online' },
      { id: 'C', text: 'A game we play offline' },
      { id: 'D', text: 'A paper we are given at a wedding' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q021',
    topic: 'coding',
    type: 'single',
    text: 'A type of programming language that contains English words is a ?',
    options: [
      { id: 'A', text: 'Scripting Language' },
      { id: 'B', text: 'Low-level Language' },
      { id: 'C', text: 'Machine Language' },
      { id: 'D', text: 'High-level Language' },
    ],
    correctOptionIds: ['D'],
  },
  {
    id: 'Q022',
    topic: 'coding',
    type: 'multi',
    text: 'Select all high-level languages.',
    options: [
      { id: 'A', text: 'Python' },
      { id: 'B', text: 'Java' },
      { id: 'C', text: 'Bash' },
      { id: 'D', text: 'Javascript' },
    ],
    correctOptionIds: ['A', 'B', 'D'],
  },
  {
    id: 'Q023',
    topic: 'basics',
    type: 'multi',
    text: 'Pick all input devices.',
    options: [
      { id: 'A', text: 'Mouse' },
      { id: 'B', text: 'Keyboard' },
      { id: 'C', text: 'Scanner' },
      { id: 'D', text: 'Monitor' },
    ],
    correctOptionIds: ['A', 'B', 'C'],
  },

  {
    id: 'Q024',
    topic: 'navigation',
    type: 'single',
    text: 'Right-click usually opens...',
    options: [
      { id: 'A', text: 'A shortcut menu' },
      { id: 'B', text: 'The power button' },
      { id: 'C', text: 'The internet' },
      { id: 'D', text: 'A camera app' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q025',
    topic: 'navigation',
    type: 'single',
    text: 'To create a folder on desktop, first do...',
    options: [
      { id: 'A', text: 'Right-click on empty desktop area' },
      { id: 'B', text: 'Turn off computer' },
      { id: 'C', text: 'Press Caps Lock' },
      { id: 'D', text: 'Remove battery' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q026',
    topic: 'navigation',
    type: 'single',
    text: 'To rename a file, choose...',
    options: [
      { id: 'A', text: 'Rename' },
      { id: 'B', text: 'Delete' },
      { id: 'C', text: 'Refresh' },
      { id: 'D', text: 'Print' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q027',
    topic: 'navigation',
    type: 'single',
    text: 'Which shortcut switches between open application windows?',
    options: [
      { id: 'A', text: 'Alt + Tab' },
      { id: 'B', text: 'Ctrl + P' },
      { id: 'C', text: 'Alt + F4' },
      { id: 'D', text: 'Ctrl + N' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q028',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for copy is...',
    options: [
      { id: 'A', text: 'Ctrl + C' },
      { id: 'B', text: 'Ctrl + X' },
      { id: 'C', text: 'Ctrl + V' },
      { id: 'D', text: 'Ctrl + Z' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q029',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for paste is...',
    options: [
      { id: 'A', text: 'Ctrl + Z' },
      { id: 'B', text: 'Ctrl + V' },
      { id: 'C', text: 'Ctrl + C' },
      { id: 'D', text: 'Ctrl + S' },
    ],
    correctOptionIds: ['B'],
  },
  {
    id: 'Q030',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for cut is...',
    options: [
      { id: 'A', text: 'Ctrl + X' },
      { id: 'B', text: 'Ctrl + A' },
      { id: 'C', text: 'Ctrl + P' },
      { id: 'D', text: 'Ctrl + R' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q031',
    topic: 'navigation',
    type: 'single',
    text: 'Keyboard shortcut for undo is...',
    options: [
      { id: 'A', text: 'Ctrl + Z' },
      { id: 'B', text: 'Ctrl + V' },
      { id: 'C', text: 'Ctrl + T' },
      { id: 'D', text: 'Ctrl + W' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q032',
    topic: 'web',
    type: 'single',
    text: 'What html tag is used to create a new line?',
    options: [
      { id: 'A', text: '<a>' },
      { id: 'B', text: '<br>' },
      { id: 'C', text: '<p>' },
      { id: 'D', text: '<img>' },
    ],
    correctOptionIds: ['B'],
  },
  {
    id: 'Q033',
    topic: 'web',
    type: 'single',
    text: 'What html tag is used to bolden text?',
    options: [
      { id: 'A', text: '<s>' },
      { id: 'B', text: '<del>' },
      { id: 'C', text: '<sup>' },
      { id: 'D', text: '<b>' },
    ],
    correctOptionIds: ['D'],
  },

  {
    id: 'Q034',
    topic: 'vscode',
    type: 'single',
    text: 'Which html tag would you use to square a number?',
    options: [
      { id: 'A', text: '<sup>' },
      { id: 'B', text: '<sub>' },
      { id: 'C', text: '<square>' },
      { id: 'D', text: '<i dont know>' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q035',
    topic: 'basics',
    type: 'multi',
    text: 'Select all the importances of programming?',
    options: [
      { id: 'A', text: 'Computers are better at solving complex mathematical equations' },
      { id: 'B', text: 'Automation' },
      { id: 'C', text: 'It makes food taste better in the pot' },
      { id: 'D', text: 'Photosynthesis' },
    ],
    correctOptionIds: ['A', 'B'],
  },
  {
    id: 'Q036',
    topic: 'vscode',
    type: 'single',
    text: 'In VS Code, to create a new file, click...',
    options: [
      { id: 'A', text: 'New File' },
      { id: 'B', text: 'Delete File' },
      { id: 'C', text: 'Print File' },
      { id: 'D', text: 'Close Folder' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q037',
    topic: 'vscode',
    type: 'single',
    text: 'Shortcut to save in VS Code is...',
    options: [
      { id: 'A', text: 'Ctrl + L' },
      { id: 'B', text: 'Ctrl + G' },
      { id: 'C', text: 'Ctrl + S' },
      { id: 'D', text: 'Ctrl + Y' },
    ],
    correctOptionIds: ['C'],
  },
  {
    id: 'Q038',
    topic: 'web',
    type: 'single',
    text: 'A website is a collection of linked _______ ',
    options: [
      { id: 'A', text: 'Computer' },
      { id: 'B', text: 'Screens' },
      { id: 'C', text: 'Webpages' },
      { id: 'D', text: 'Browsers' },
    ],
    correctOptionIds: ['C'],
  },

  {
    id: 'Q039',
    topic: 'web',
    type: 'single',
    text: 'In the header tag (<h1> to <h6>), as the number increases, the size _______',
    options: [
      { id: 'A', text: 'Decreases' },
      { id: 'B', text: 'Increases' },
      { id: 'C', text: 'Is the same' },
      { id: 'D', text: 'I was sleeping when you taught this one' },
    ],
    correctOptionIds: ['A'],
  },
  {
    id: 'Q040',
    topic: 'web',
    type: 'single',
    text: 'True or False, <head> contains metadata',
    options: [
      { id: 'A', text: 'False' },
      { id: 'B', text: 'True' },
      { id: 'C', text: 'This one is too hard' },
      { id: 'D', text: 'It is both true and false' },
    ],
    correctOptionIds: ['B'],
  },
];
